# app configuration
VERBOSE 			= False
OUTPUT_ENCODING		= 'utf-8'
OUTPUT_FORMAT		= '.csv'
DELIMITER			= '|'

# app default variables
EXPORT_DIR			= 'export/'
URL 				= 'http://tieba.baidu.com/p/2701957058'

TITLE_START 		= '<h1 class="core_title_txt"'
TITLE_END			= '</h1>'
UID_START			= '<li class="d_name'
UID_END				= '/li>'
A_START				= '<a'
A_END				= '/a>'
TAIL_START			= '<ul class="p_mtail'
TAIL_END			= '</ul>'
FROM_START			= '<a'
FROM_END			= '</a>'
POST_START			= '<div id="post_content'
POST_END			= '</div>'
PAGER_START			= '<li class="l_pager'
PAGER_END			= '</li>'
REPLIES_START		= '<li class="lzl_single_post'
REPLIES_END			= '</li>'
PID_START			= 'pid'
PID_END				= ','
REPLY_AUTH_START	= '<div class="lzl_cnt">'
REPLY_AUTH_END		= '</div>'
REPLY_CONT_START	= '<span class="lzl_content_main">'
REPLY_CONT_END		= '</span>'
